name: Output issues
on:
    issues:
        types: [opened]
    workflow_dispatch:

jobs:
    log:
        runs-on: ubuntu-22.04
        steps:
            - name: Output event details
              run: echo "${{ toJSON(github) }}"
